# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'downloadImage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for downloadImage
  pod 'AFNetworking'
  pod 'JSONModel'
  pod 'FlickrKit'
  target 'downloadImageTests' do
    inherit! :search_paths
    # Pods for testing
  
  end

  target 'downloadImageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
